services:
  postgres:
    image: postgres:latest
    container_name: blocklist-db
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  # backend:
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #   container_name: backend
  #   ports:
  #     - "3000:3000"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/prisma

volumes:
  postgres-data:
