import z from "zod";
import { TaskCreateManyInputSchema } from "../generated/zod";

export type TaskCreateInput = Omit<
  z.infer<typeof TaskCreateManyInputSchema>,
  "taskId"
>;

const tasks: TaskCreateInput[] = [
  {
    name: "Finish project",
    description: "Complete all the outstanding tasks and submit the project",
    importance: "high",
    userId: 1,
    startRow: 0,
    startCol: 0,
    endRow: 2,
    endCol: 1,
  },
  {
    name: "Research",
    description: "Do research on a new topic for the next project",
    importance: "medium",
    userId: 1,
    startRow: 0,
    startCol: 2,
    endRow: 2,
    endCol: 3,
  },
  {
    name: "Prepare presentation",
    description: "Prepare a presentation for the next meeting",
    importance: "high",
    userId: 1,
    startRow: 3,
    startCol: 0,
    endRow: 7,
    endCol: 0,
  },
  {
    name: "Email clients",
    description:
      "Send an email to all the clients to update them on the project",
    importance: "low",
    userId: 2,
    startRow: 3,
    startCol: 1,
    endRow: 3,
    endCol: 3,
  },
  {
    name: "Schedule meeting",
    description: "Schedule a meeting with the team to discuss the project",
    importance: "medium",
    userId: 2,
    startRow: 5,
    startCol: 1,
    endRow: 7,
    endCol: 2,
  },
  {
    name: "Complete subtask 1",
    description: "Finish subtask 1 under task 4",
    importance: "medium",
    userId: 1,
    startRow: 5,
    startCol: 3,
    endRow: 7,
    endCol: 3,
  },
  {
    name: "Complete subtask 2",
    description: "Finish subtask 2 under task 4",
    importance: "low",
    parentTaskId: 6,
    userId: 1,
    startRow: 1,
    startCol: 1,
    endRow: 1,
    endCol: 1,
  },
  {
    name: "Complete subtask 3",
    description: "Finish subtask 3 under task 4",
    importance: "medium",
    parentTaskId: 6,
    userId: 1,
    startRow: 1,
    startCol: 1,
    endRow: 1,
    endCol: 1,
  },
  {
    name: "Complete subtask 4",
    description: "Finish subtask 4 under task 4",
    importance: "high",
    parentTaskId: 6,
    userId: 1,
    startRow: 1,
    startCol: 1,
    endRow: 1,
    endCol: 1,
  },
  {
    name: "Complete subtask 5",
    description: "Finish subtask 5 under task 4",
    importance: "medium",
    parentTaskId: 6,
    userId: 1,
    startRow: 1,
    startCol: 1,
    endRow: 1,
    endCol: 1,
  },
  {
    name: "Complete subtask 6",
    description: "Finish subtask 6 under task 4",
    importance: "low",
    parentTaskId: 6,
    userId: 1,
    startRow: 1,
    startCol: 1,
    endRow: 1,
    endCol: 1,
  },
  {
    name: "Complete subtask 9",
    description: "Finish subtask 9 under task 4",
    importance: "medium",
    parentTaskId: 7,
    userId: 1,
    startRow: 1,
    startCol: 1,
    endRow: 1,
    endCol: 1,
  },
];

export default tasks;
